#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_104991_BP

#include "Basic.hpp"

#include "PyAbility_104991_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_104991_BP.Ability_104991_BP_C
// 0x0000 (0x2CC0 - 0x2CC0)
class UAbility_104991_BP_C final : public UPyAbility_104991
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_104991_BP_C">();
	}
	static class UAbility_104991_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_104991_BP_C>();
	}
};
static_assert(alignof(UAbility_104991_BP_C) == 0x000008, "Wrong alignment on UAbility_104991_BP_C");
static_assert(sizeof(UAbility_104991_BP_C) == 0x002CC0, "Wrong size on UAbility_104991_BP_C");

}

