#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_101198_BP

#include "Basic.hpp"

#include "PyAbility_101198_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_101198_BP.Ability_101198_BP_C
// 0x0000 (0x25C8 - 0x25C8)
class UAbility_101198_BP_C final : public UPyAbility_101198
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_101198_BP_C">();
	}
	static class UAbility_101198_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_101198_BP_C>();
	}
};
static_assert(alignof(UAbility_101198_BP_C) == 0x000008, "Wrong alignment on UAbility_101198_BP_C");
static_assert(sizeof(UAbility_101198_BP_C) == 0x0025C8, "Wrong size on UAbility_101198_BP_C");

}

