#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_102982_BP

#include "Basic.hpp"

#include "PyAbility_102982_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Ability_102982_BP.Ability_102982_BP_C
// 0x0000 (0x2808 - 0x2808)
class UAbility_102982_BP_C final : public UPyAbility_102982
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Ability_102982_BP_C">();
	}
	static class UAbility_102982_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAbility_102982_BP_C>();
	}
};
static_assert(alignof(UAbility_102982_BP_C) == 0x000008, "Wrong alignment on UAbility_102982_BP_C");
static_assert(sizeof(UAbility_102982_BP_C) == 0x002808, "Wrong size on UAbility_102982_BP_C");

}

