#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Ability_105224_BP

#include "Basic.hpp"

#include "Ability_105224_BP_classes.hpp"
#include "Ability_105224_BP_parameters.hpp"


namespace SDK
{

// Function Ability_105224_BP.Ability_105224_BP_C.CanActivate
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UAbility_105224_BP_C::CanActivate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_105224_BP_C", "CanActivate");

	Params::Ability_105224_BP_C_CanActivate Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Ability_105224_BP.Ability_105224_BP_C.ExecuteUbergraph_Ability_105224_BP
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAbility_105224_BP_C::ExecuteUbergraph_Ability_105224_BP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_105224_BP_C", "ExecuteUbergraph_Ability_105224_BP");

	Params::Ability_105224_BP_C_ExecuteUbergraph_Ability_105224_BP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Ability_105224_BP.Ability_105224_BP_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UAbility_105224_BP_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_105224_BP_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Ability_105224_BP.Ability_105224_BP_C.PreMissileEventNotify
// (Event, Public, BlueprintEvent)

void UAbility_105224_BP_C::PreMissileEventNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Ability_105224_BP_C", "PreMissileEventNotify");

	UObject::ProcessEvent(Func, nullptr);
}

}

