#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIAbilityActivation_LunaSnowSwitchState

#include "Basic.hpp"

#include "Ability_activation_logic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIAbilityActivation_LunaSnowSwitchState.AIAbilityActivation_LunaSnowSwitchState_C
// 0x0000 (0x0058 - 0x0058)
class UAIAbilityActivation_LunaSnowSwitchState_C final : public UPyAIAbilityActivation_LunaSnowSwitchState
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AIAbilityActivation_LunaSnowSwitchState_C">();
	}
	static class UAIAbilityActivation_LunaSnowSwitchState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAIAbilityActivation_LunaSnowSwitchState_C>();
	}
};
static_assert(alignof(UAIAbilityActivation_LunaSnowSwitchState_C) == 0x000008, "Wrong alignment on UAIAbilityActivation_LunaSnowSwitchState_C");
static_assert(sizeof(UAIAbilityActivation_LunaSnowSwitchState_C) == 0x000058, "Wrong size on UAIAbilityActivation_LunaSnowSwitchState_C");

}

