#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: One039_CharacterBP

#include "Basic.hpp"

#include "PyThorCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 1039_CharacterBP.1039_CharacterBP_C
// 0x0010 (0x17D0 - 0x17C0)
class AOne039_CharacterBP_C final : public APyThorCharacter
{
public:
	class UPhysicalInteractionComponent*          PhysicalInteraction;                               // 0x17C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1039_CharacterBP_C">();
	}
	static class AOne039_CharacterBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOne039_CharacterBP_C>();
	}
};
static_assert(alignof(AOne039_CharacterBP_C) == 0x000010, "Wrong alignment on AOne039_CharacterBP_C");
static_assert(sizeof(AOne039_CharacterBP_C) == 0x0017D0, "Wrong size on AOne039_CharacterBP_C");
static_assert(offsetof(AOne039_CharacterBP_C, PhysicalInteraction) == 0x0017C0, "Member 'AOne039_CharacterBP_C::PhysicalInteraction' has a wrong offset!");

}

