#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: One038_CharacterBP

#include "Basic.hpp"

#include "PyScarletWitchCharacter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass 1038_CharacterBP.1038_CharacterBP_C
// 0x0000 (0x17C0 - 0x17C0)
class AOne038_CharacterBP_C final : public APyScarletWitchCharacter
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"1038_CharacterBP_C">();
	}
	static class AOne038_CharacterBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AOne038_CharacterBP_C>();
	}
};
static_assert(alignof(AOne038_CharacterBP_C) == 0x000010, "Wrong alignment on AOne038_CharacterBP_C");
static_assert(sizeof(AOne038_CharacterBP_C) == 0x0017C0, "Wrong size on AOne038_CharacterBP_C");

}

