#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PC_UISettingEntryScalabilityHandlerBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Marvel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PC_UISettingEntryScalabilityHandlerBP.PC_UISettingEntryScalabilityHandlerBP_C
// 0x00C0 (0x00F0 - 0x0030)
class UPC_UISettingEntryScalabilityHandlerBP_C final : public UUISettingEntrySettingHandler
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0030(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         View_distance_quality;                             // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Shadow_quality;                                    // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Global_illumination_quality;                       // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Reflection_quality;                                // 0x0044(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Texture_quality;                                   // 0x0048(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Visual_effect_quality;                             // 0x004C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Post_processing_quality;                           // 0x0050(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Foliage_quality;                                   // 0x0054(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Shading_quality;                                   // 0x0058(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         Tag_refresh;                                       // 0x0060(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                 SettingQuality;                                    // 0x0070(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                 SettingQuality_WithoutReflection;                  // 0x0080(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                 Low80;                                             // 0x0090(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                 Low80gi1;                                          // 0x00A0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                 Mid81gi2;                                          // 0x00B0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                 High82;                                            // 0x00C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<int32>                                 Epic93;                                            // 0x00D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<class FString>                         Tag_refresh_scalability;                           // 0x00E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	float BP_GetCurrentValue(class UObject* Object, const class FString& SettingKey, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS);
	void BP_OnApply(class UObject* Object, const class FString& SettingKey, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value);
	TMap<class FString, int32> BP_OnChanged(class UObject* Object, const class FString& SettingKey, const TMap<class FString, class FString>& Params_0, const TMap<int32, class FText>& OPTIONS, float Value, const TMap<class FString, int32>& CurrentTags);
	void ExecuteUbergraph_PC_UISettingEntryScalabilityHandlerBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PC_UISettingEntryScalabilityHandlerBP_C">();
	}
	static class UPC_UISettingEntryScalabilityHandlerBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPC_UISettingEntryScalabilityHandlerBP_C>();
	}
};
static_assert(alignof(UPC_UISettingEntryScalabilityHandlerBP_C) == 0x000008, "Wrong alignment on UPC_UISettingEntryScalabilityHandlerBP_C");
static_assert(sizeof(UPC_UISettingEntryScalabilityHandlerBP_C) == 0x0000F0, "Wrong size on UPC_UISettingEntryScalabilityHandlerBP_C");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, UberGraphFrame) == 0x000030, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, View_distance_quality) == 0x000038, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::View_distance_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Shadow_quality) == 0x00003C, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Shadow_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Global_illumination_quality) == 0x000040, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Global_illumination_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Reflection_quality) == 0x000044, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Reflection_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Texture_quality) == 0x000048, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Texture_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Visual_effect_quality) == 0x00004C, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Visual_effect_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Post_processing_quality) == 0x000050, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Post_processing_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Foliage_quality) == 0x000054, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Foliage_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Shading_quality) == 0x000058, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Shading_quality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Tag_refresh) == 0x000060, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Tag_refresh' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, SettingQuality) == 0x000070, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::SettingQuality' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, SettingQuality_WithoutReflection) == 0x000080, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::SettingQuality_WithoutReflection' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Low80) == 0x000090, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Low80' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Low80gi1) == 0x0000A0, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Low80gi1' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Mid81gi2) == 0x0000B0, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Mid81gi2' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, High82) == 0x0000C0, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::High82' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Epic93) == 0x0000D0, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Epic93' has a wrong offset!");
static_assert(offsetof(UPC_UISettingEntryScalabilityHandlerBP_C, Tag_refresh_scalability) == 0x0000E0, "Member 'UPC_UISettingEntryScalabilityHandlerBP_C::Tag_refresh_scalability' has a wrong offset!");

}

