#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103382

#include "Basic.hpp"

#include "PyAbility_135_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_103382.PyAbility_103382
// 0x0000 (0x2550 - 0x2550)
class UPyAbility_103382 : public UPyAbility_135
{
public:
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103382">();
	}
	static class UPyAbility_103382* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103382>();
	}
};
static_assert(alignof(UPyAbility_103382) == 0x000008, "Wrong alignment on UPyAbility_103382");
static_assert(sizeof(UPyAbility_103382) == 0x002550, "Wrong size on UPyAbility_103382");

}

