#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_200209

#include "Basic.hpp"

#include "Marvel_classes.hpp"
#include "Engine_structs.hpp"
#include "DeclarativeUnreal_structs.hpp"


namespace SDK
{

// PythonClass PyAbility_200209.PyAbility_200209
// 0x0008 (0x1178 - 0x1170)
class UPyAbility_200209 : public UMarvelBlindAbility
{
public:
	int32                                         Scope;                                             // 0x1170(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void K2_ActivateAbility();
	void GetMarvelAbilityID();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_200209">();
	}
	static class UPyAbility_200209* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_200209>();
	}
};
static_assert(alignof(UPyAbility_200209) == 0x000008, "Wrong alignment on UPyAbility_200209");
static_assert(sizeof(UPyAbility_200209) == 0x001178, "Wrong size on UPyAbility_200209");
static_assert(offsetof(UPyAbility_200209, Scope) == 0x001170, "Member 'UPyAbility_200209::Scope' has a wrong offset!");

// PythonClass PyAbility_200209.PyTraceComponent_20020901
// 0x0000 (0x16B0 - 0x16B0)
class UPyTraceComponent_20020901 final : public UMarvelAgentTraceComponent
{
public:
	void ReceiveBeginPlay();
	void K2_Initialize();
	void K2_Finalize();
	void K2_OnPreTrace();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTraceComponent_20020901">();
	}
	static class UPyTraceComponent_20020901* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyTraceComponent_20020901>();
	}
};
static_assert(alignof(UPyTraceComponent_20020901) == 0x000010, "Wrong alignment on UPyTraceComponent_20020901");
static_assert(sizeof(UPyTraceComponent_20020901) == 0x0016B0, "Wrong size on UPyTraceComponent_20020901");

// PythonClass PyAbility_200209.PyCue_Buff_Loop_20020901
// 0x0020 (0x1008 - 0x0FE8)
class APyCue_Buff_Loop_20020901 final : public AMarvelCueNotify_Buff
{
public:
	TArray<EObjectTypeQuery>                      TraceSceneObjectType;                              // 0x0FE8(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FDeclarationHolder                     ViewTargetWatcher;                                 // 0x0FF8(0x0010)(BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void ReceiveTick(float DeltaSeconds);
	void WhileActiveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);
	void OnRemoveFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyCue_Buff_Loop_20020901">();
	}
	static class APyCue_Buff_Loop_20020901* GetDefaultObj()
	{
		return GetDefaultObjImpl<APyCue_Buff_Loop_20020901>();
	}
};
static_assert(alignof(APyCue_Buff_Loop_20020901) == 0x000008, "Wrong alignment on APyCue_Buff_Loop_20020901");
static_assert(sizeof(APyCue_Buff_Loop_20020901) == 0x001008, "Wrong size on APyCue_Buff_Loop_20020901");
static_assert(offsetof(APyCue_Buff_Loop_20020901, TraceSceneObjectType) == 0x000FE8, "Member 'APyCue_Buff_Loop_20020901::TraceSceneObjectType' has a wrong offset!");
static_assert(offsetof(APyCue_Buff_Loop_20020901, ViewTargetWatcher) == 0x000FF8, "Member 'APyCue_Buff_Loop_20020901::ViewTargetWatcher' has a wrong offset!");

}

