#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_102951

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAbility_102951.PyTraceComponent_10295101_Base
// 0x0000 (0x16B0 - 0x16B0)
class UPyTraceComponent_10295101_Base final : public UMarvelAgentTraceComponent
{
public:
	struct FVector K2_OnGetTraceStart(struct FVector& Location);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyTraceComponent_10295101_Base">();
	}
	static class UPyTraceComponent_10295101_Base* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyTraceComponent_10295101_Base>();
	}
};
static_assert(alignof(UPyTraceComponent_10295101_Base) == 0x000010, "Wrong alignment on UPyTraceComponent_10295101_Base");
static_assert(sizeof(UPyTraceComponent_10295101_Base) == 0x0016B0, "Wrong size on UPyTraceComponent_10295101_Base");

}

