#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_103613

#include "Basic.hpp"

#include "Hero_1036_structs.hpp"
#include "Marvel_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PyAbility_103613.PyConfig_103613
// 0x0028 (0x00C0 - 0x0098)
class UPyConfig_103613 final : public UMarvelAbilityConfig
{
public:
	TArray<struct FReduceCDItem>                  RCDs;                                              // 0x0098(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	struct FVector                                LaunchVelocity;                                    // 0x00A8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyConfig_103613">();
	}
	static class UPyConfig_103613* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyConfig_103613>();
	}
};
static_assert(alignof(UPyConfig_103613) == 0x000008, "Wrong alignment on UPyConfig_103613");
static_assert(sizeof(UPyConfig_103613) == 0x0000C0, "Wrong size on UPyConfig_103613");
static_assert(offsetof(UPyConfig_103613, RCDs) == 0x000098, "Member 'UPyConfig_103613::RCDs' has a wrong offset!");
static_assert(offsetof(UPyConfig_103613, LaunchVelocity) == 0x0000A8, "Member 'UPyConfig_103613::LaunchVelocity' has a wrong offset!");

// PythonClass PyAbility_103613.PyAbility_103613
// 0x0000 (0x2558 - 0x2558)
class UPyAbility_103613 : public UAbility_108
{
public:
	void BeginPlay();
	bool CanActivate();
	void K2_ActivateAbility();
	void MissileEventNotify();
	void K2_OnEndAbility(bool bWasCancelled);
	void EndPlay();
	void OnSkillActivate(class UGameplayAbility* Ability);
	void OnSkillMissile(class UGameplayAbility* Ability);
	void OnSkillBreaked(class UGameplayAbility* Ability);
	void OnSkillEnded(class UGameplayAbility* Ability);
	void OnSkillDamage(class UGameplayAbility* Ability, const struct FAttributeModifierHandle& ParamHandle);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAbility_103613">();
	}
	static class UPyAbility_103613* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAbility_103613>();
	}
};
static_assert(alignof(UPyAbility_103613) == 0x000008, "Wrong alignment on UPyAbility_103613");
static_assert(sizeof(UPyAbility_103613) == 0x002558, "Wrong size on UPyAbility_103613");

// PythonClass PyAbility_103613.PyUIController_103613
// 0x0018 (0x0C70 - 0x0C58)
class UPyUIController_103613 final : public UUIC_Ability
{
public:
	class UTexture2D*                             Icon103611;                                        // 0x0C58(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             Icon103613;                                        // 0x0C60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UTexture2D*                             Icon103614;                                        // 0x0C68(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInit();
	void SetAbility(int32 InAbilityId, class UGameplayAbility* InAbility);
	void Destruct();
	void OnTagUpdate(const struct FGameplayTag& Tag, bool Exist);
	void OnMovementModeChanged(class ACharacter* Char, EMovementMode Pre, uint8 Precustom);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyUIController_103613">();
	}
	static class UPyUIController_103613* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyUIController_103613>();
	}
};
static_assert(alignof(UPyUIController_103613) == 0x000008, "Wrong alignment on UPyUIController_103613");
static_assert(sizeof(UPyUIController_103613) == 0x000C70, "Wrong size on UPyUIController_103613");
static_assert(offsetof(UPyUIController_103613, Icon103611) == 0x000C58, "Member 'UPyUIController_103613::Icon103611' has a wrong offset!");
static_assert(offsetof(UPyUIController_103613, Icon103613) == 0x000C60, "Member 'UPyUIController_103613::Icon103613' has a wrong offset!");
static_assert(offsetof(UPyUIController_103613, Icon103614) == 0x000C68, "Member 'UPyUIController_103613::Icon103614' has a wrong offset!");

}

