#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAbility_104241

#include "Basic.hpp"

#include "PyAbility_104241_classes.hpp"
#include "PyAbility_104241_parameters.hpp"


namespace SDK
{

// PythonFunction PyAbility_104241.PyAbility_104241.BeginPlay
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPyAbility_104241::BeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAbility_104241", "BeginPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyAbility_104241.K2_ActivateAbility
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPyAbility_104241::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAbility_104241", "K2_ActivateAbility");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyAbility_104241.OnActivateActionPressed
// (Native, Public, BlueprintCallable)
// Parameters:
// float                                   TimeWaited                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyAbility_104241::OnActivateActionPressed(float TimeWaited)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAbility_104241", "OnActivateActionPressed");

	Params::PyAbility_104241_OnActivateActionPressed Parms{};

	Parms.TimeWaited = TimeWaited;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyAbility_104241.OnConfirmEvent
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FGameplayAbilityTargetDataHandle Data                                                   (ConstParm, Parm, OutParm, ReferenceParm)

void UPyAbility_104241::OnConfirmEvent(const struct FGameplayAbilityTargetDataHandle& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAbility_104241", "OnConfirmEvent");

	Params::PyAbility_104241_OnConfirmEvent Parms{};

	Parms.Data = std::move(Data);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyAbility_104241.OnCancelEvent
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FGameplayAbilityTargetDataHandle Data                                                   (ConstParm, Parm, OutParm, ReferenceParm)

void UPyAbility_104241::OnCancelEvent(const struct FGameplayAbilityTargetDataHandle& Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAbility_104241", "OnCancelEvent");

	Params::PyAbility_104241_OnCancelEvent Parms{};

	Parms.Data = std::move(Data);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyAbility_104241.MissileEventNotify
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPyAbility_104241::MissileEventNotify()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAbility_104241", "MissileEventNotify");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyAbility_104241.K2_OnEndAbility
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPyAbility_104241::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAbility_104241", "K2_OnEndAbility");

	Params::PyAbility_104241_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// DelegateFunction PyAbility_104241.PySummonedComp_10424101.OnElectronicNestEndTask__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void UPySummonedComp_10424101::OnElectronicNestEndTask__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnElectronicNestEndTask__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyAbility_104241.PySummonedComp_10424101.OnStateChange__DelegateSignature
// (MulticastDelegate, Public, Delegate)
// Parameters:
// EState_10424101                         NewState                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPySummonedComp_10424101::OnStateChange__DelegateSignature(EState_10424101 NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnStateChange__DelegateSignature");

	Params::PySummonedComp_10424101_OnStateChange__DelegateSignature Parms{};

	Parms.NewState = NewState;

	UObject::ProcessEvent(Func, &Parms);
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.EndPlay
// (Native, Public, BlueprintCallable)

void UPySummonedComp_10424101::EndPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "EndPlay");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.SetState
// (Native, Public, BlueprintCallable)
// Parameters:
// EState_10424101                         NewState                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPySummonedComp_10424101::SetState(EState_10424101 NewState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "SetState");

	Params::PySummonedComp_10424101_SetState Parms{};

	Parms.NewState = NewState;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.UpdateState
// (Native, Public, BlueprintCallable)

void UPySummonedComp_10424101::UpdateState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "UpdateState");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnRep_State
// (Native, Public, BlueprintCallable)

void UPySummonedComp_10424101::OnRep_State()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnRep_State");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnRep_Event
// (Native, Public, BlueprintCallable)

void UPySummonedComp_10424101::OnRep_Event()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnRep_Event");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnWebActivated
// (Native, Public, BlueprintCallable)

void UPySummonedComp_10424101::OnWebActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnWebActivated");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.SetEvent
// (Native, Public, BlueprintCallable)
// Parameters:
// EEvent_10424101                         NewEvent                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPySummonedComp_10424101::SetEvent(EEvent_10424101 NewEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "SetEvent");

	Params::PySummonedComp_10424101_SetEvent Parms{};

	Parms.NewEvent = NewEvent;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.K2_OnBeginAgentTask
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424101::K2_OnBeginAgentTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "K2_OnBeginAgentTask");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.K2_OnEndAgentTask
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424101::K2_OnEndAgentTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "K2_OnEndAgentTask");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.K2_OnRecycleAgentTask
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424101::K2_OnRecycleAgentTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "K2_OnRecycleAgentTask");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.MulticastLaunch
// (Net, NetReliable, Native, NetMulticast, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FVector                          StartLocation                                          (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Velocity                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPySummonedComp_10424101::MulticastLaunch(const struct FVector& StartLocation, const struct FVector& Velocity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "MulticastLaunch");

	Params::PySummonedComp_10424101_MulticastLaunch Parms{};

	Parms.StartLocation = std::move(StartLocation);
	Parms.Velocity = std::move(Velocity);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnProjectileHit
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FHitResult                       Hit                                                    (ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)

void UPySummonedComp_10424101::OnProjectileHit(const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnProjectileHit");

	Params::PySummonedComp_10424101_OnProjectileHit Parms{};

	Parms.Hit = std::move(Hit);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnAttachActorDestroyed
// (Native, Public, BlueprintCallable)
// Parameters:
// class UGeometryCollectionComponent*     Component                                              (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FName                             Name_0                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPySummonedComp_10424101::OnAttachActorDestroyed(class UGeometryCollectionComponent* Component, class FName Name_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnAttachActorDestroyed");

	Params::PySummonedComp_10424101_OnAttachActorDestroyed Parms{};

	Parms.Component = Component;
	Parms.Name_0 = Name_0;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnChaosBroken
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FChaosBreakEvent                 BreakEvent                                             (ConstParm, Parm, OutParm, ReferenceParm, NoDestructor)

void UPySummonedComp_10424101::OnChaosBroken(const struct FChaosBreakEvent& BreakEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnChaosBroken");

	Params::PySummonedComp_10424101_OnChaosBroken Parms{};

	Parms.BreakEvent = std::move(BreakEvent);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnAttachComponentFracture
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FVector                          Point                                                  (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          Direction                                              (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPySummonedComp_10424101::OnAttachComponentFracture(const struct FVector& Point, const struct FVector& Direction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnAttachComponentFracture");

	Params::PySummonedComp_10424101_OnAttachComponentFracture Parms{};

	Parms.Point = std::move(Point);
	Parms.Direction = std::move(Direction);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnPresetDestuctionBegin
// (Native, Public, BlueprintCallable)
// Parameters:
// class FName                             LevelName                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPySummonedComp_10424101::OnPresetDestuctionBegin(class FName LevelName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnPresetDestuctionBegin");

	Params::PySummonedComp_10424101_OnPresetDestuctionBegin Parms{};

	Parms.LevelName = LevelName;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424101.OnMovementPlaced
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424101::OnMovementPlaced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424101", "OnMovementPlaced");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummoned_10424101.GetCurrentState
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EState_10424101                         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

EState_10424101 APySummoned_10424101::GetCurrentState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummoned_10424101", "GetCurrentState");

	Params::PySummoned_10424101_GetCurrentState Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424102.K2_OnBeginAgentTask
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424102::K2_OnBeginAgentTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424102", "K2_OnBeginAgentTask");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424102.OnNestEndTask
// (Native, Public, BlueprintCallable)

void UPySummonedComp_10424102::OnNestEndTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424102", "OnNestEndTask");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424102.K2_OnEndAgentTask
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424102::K2_OnEndAgentTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424102", "K2_OnEndAgentTask");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonerLoop_10424101_Cue.WhileActive
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APySummonerLoop_10424101_Cue::WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424101_Cue", "WhileActive");

	Params::PySummonerLoop_10424101_Cue_WhileActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyAbility_104241.PySummonerLoop_10424101_Cue.OnExecuteFX
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)

void APySummonerLoop_10424101_Cue::OnExecuteFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424101_Cue", "OnExecuteFX");

	Params::PySummonerLoop_10424101_Cue_OnExecuteFX Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonerLoop_10424101_Cue.OnRemove
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APySummonerLoop_10424101_Cue::OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424101_Cue", "OnRemove");

	Params::PySummonerLoop_10424101_Cue_OnRemove Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// DelegateFunction PyAbility_104241.PySummonerLoop_10424102_Cue.OnStopMoveDelegate__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APySummonerLoop_10424102_Cue::OnStopMoveDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424102_Cue", "OnStopMoveDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyAbility_104241.PySummonerLoop_10424102_Cue.OnBeginMoveDelegate__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APySummonerLoop_10424102_Cue::OnBeginMoveDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424102_Cue", "OnBeginMoveDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// PythonFunction PyAbility_104241.PySummonerLoop_10424102_Cue.WhileActiveAudio
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)

void APySummonerLoop_10424102_Cue::WhileActiveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424102_Cue", "WhileActiveAudio");

	Params::PySummonerLoop_10424102_Cue_WhileActiveAudio Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonerLoop_10424102_Cue.OnRemoveAudio
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)

void APySummonerLoop_10424102_Cue::OnRemoveAudio(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424102_Cue", "OnRemoveAudio");

	Params::PySummonerLoop_10424102_Cue_OnRemoveAudio Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonerLoop_10424103_Cue.WhileActive
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APySummonerLoop_10424103_Cue::WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424103_Cue", "WhileActive");

	Params::PySummonerLoop_10424103_Cue_WhileActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyAbility_104241.PySummonerLoop_10424103_Cue.OnExecuteFX
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)

void APySummonerLoop_10424103_Cue::OnExecuteFX(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonerLoop_10424103_Cue", "OnExecuteFX");

	Params::PySummonerLoop_10424103_Cue_OnExecuteFX Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.WhileActive
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APyCue_Summoner_Loop_10424105::WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "WhileActive");

	Params::PyCue_Summoner_Loop_10424105_WhileActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.OnRemove
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APyCue_Summoner_Loop_10424105::OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "OnRemove");

	Params::PyCue_Summoner_Loop_10424105_OnRemove Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.K2_OnWebActivated
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void APyCue_Summoner_Loop_10424105::K2_OnWebActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "K2_OnWebActivated");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.StartWebTimelines
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void APyCue_Summoner_Loop_10424105::StartWebTimelines()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "StartWebTimelines");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// DelegateFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.OnStartWebTimelines__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void APyCue_Summoner_Loop_10424105::OnStartWebTimelines__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "OnStartWebTimelines__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.UpdateWebScale
// (Native, Public, HasOutParams, BlueprintCallable)
// Parameters:
// struct FVector                          OutValue                                               (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyCue_Summoner_Loop_10424105::UpdateWebScale(const struct FVector& OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "UpdateWebScale");

	Params::PyCue_Summoner_Loop_10424105_UpdateWebScale Parms{};

	Parms.OutValue = std::move(OutValue);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.UpdateWebAlpha
// (Native, Public, BlueprintCallable)
// Parameters:
// class FName                             TrackName                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             PropertyName                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OutValue                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyCue_Summoner_Loop_10424105::UpdateWebAlpha(class FName TrackName, class FName PropertyName, float OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "UpdateWebAlpha");

	Params::PyCue_Summoner_Loop_10424105_UpdateWebAlpha Parms{};

	Parms.TrackName = TrackName;
	Parms.PropertyName = PropertyName;
	Parms.OutValue = OutValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.UpdateWebWPO
// (Native, Public, BlueprintCallable)
// Parameters:
// class FName                             TrackName                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             PropertyName                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OutValue                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyCue_Summoner_Loop_10424105::UpdateWebWPO(class FName TrackName, class FName PropertyName, float OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "UpdateWebWPO");

	Params::PyCue_Summoner_Loop_10424105_UpdateWebWPO Parms{};

	Parms.TrackName = TrackName;
	Parms.PropertyName = PropertyName;
	Parms.OutValue = OutValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.UpdateWebEmissive
// (Native, Public, BlueprintCallable)
// Parameters:
// class FName                             TrackName                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             PropertyName                                           (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   OutValue                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void APyCue_Summoner_Loop_10424105::UpdateWebEmissive(class FName TrackName, class FName PropertyName, float OutValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "UpdateWebEmissive");

	Params::PyCue_Summoner_Loop_10424105_UpdateWebEmissive Parms{};

	Parms.TrackName = TrackName;
	Parms.PropertyName = PropertyName;
	Parms.OutValue = OutValue;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.OnScaleFinished
// (Native, Public, BlueprintCallable)

void APyCue_Summoner_Loop_10424105::OnScaleFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "OnScaleFinished");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.OnAlphaFinished
// (Native, Public, BlueprintCallable)

void APyCue_Summoner_Loop_10424105::OnAlphaFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "OnAlphaFinished");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.OnWPOFinished
// (Native, Public, BlueprintCallable)

void APyCue_Summoner_Loop_10424105::OnWPOFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "OnWPOFinished");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Summoner_Loop_10424105.OnEmissiveFinished
// (Native, Public, BlueprintCallable)

void APyCue_Summoner_Loop_10424105::OnEmissiveFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Summoner_Loop_10424105", "OnEmissiveFinished");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_SummonerLoop_10424104.WhileActive
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APyCue_SummonerLoop_10424104::WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_SummonerLoop_10424104", "WhileActive");

	Params::PyCue_SummonerLoop_10424104_WhileActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// PythonFunction PyAbility_104241.PyCue_SummonerLoop_10424104.OnSummonedEnd
// (Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           Summoned                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void APyCue_SummonerLoop_10424104::OnSummonedEnd(class AActor* Summoned)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_SummonerLoop_10424104", "OnSummonedEnd");

	Params::PyCue_SummonerLoop_10424104_OnSummonedEnd Parms{};

	Parms.Summoned = Summoned;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_SummonerLoop_10424104.OnRemove
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APyCue_SummonerLoop_10424104::OnRemove(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_SummonerLoop_10424104", "OnRemove");

	Params::PyCue_SummonerLoop_10424104_OnRemove Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// DelegateFunction PyAbility_104241.PySummonedComp_10424103.OnLinkStateChanged__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void UPySummonedComp_10424103::OnLinkStateChanged__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424103", "OnLinkStateChanged__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// DelegateFunction PyAbility_104241.PySummonedComp_10424103.GenMeshReformDispatcher__DelegateSignature
// (MulticastDelegate, Public, Delegate)

void UPySummonedComp_10424103::GenMeshReformDispatcher__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424103", "GenMeshReformDispatcher__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// PythonFunction PyAbility_104241.PySummonedComp_10424103.K2_OnWebActive
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424103::K2_OnWebActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424103", "K2_OnWebActive");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424103.K2_OnEndAgentTask
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424103::K2_OnEndAgentTask()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424103", "K2_OnEndAgentTask");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424103.K2_OnGenMeshReform
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424103::K2_OnGenMeshReform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424103", "K2_OnGenMeshReform");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PySummonedComp_10424103.K2_OnGenMeshDestroy
// (Native, Event, Public, BlueprintCallable, BlueprintEvent)

void UPySummonedComp_10424103::K2_OnGenMeshDestroy()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PySummonedComp_10424103", "K2_OnGenMeshDestroy");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAbility_104241.PyCue_Ability_Loop_10424101.WhileActive
// (Native, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           MyTarget                                               (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// struct FGameplayCueParameters           Parameters                                             (ConstParm, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool APyCue_Ability_Loop_10424101::WhileActive(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyCue_Ability_Loop_10424101", "WhileActive");

	Params::PyCue_Ability_Loop_10424101_WhileActive Parms{};

	Parms.MyTarget = MyTarget;
	Parms.Parameters = std::move(Parameters);

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

