#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAchievementManager

#include "Basic.hpp"

#include "Marvel_classes.hpp"


namespace SDK
{

// PythonClass PyAchievementManager.PyAchievementManager
// 0x0000 (0x00B0 - 0x00B0)
class UPyAchievementManager final : public UAchievementManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyAchievementManager">();
	}
	static class UPyAchievementManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyAchievementManager>();
	}
};
static_assert(alignof(UPyAchievementManager) == 0x000008, "Wrong alignment on UPyAchievementManager");
static_assert(sizeof(UPyAchievementManager) == 0x0000B0, "Wrong size on UPyAchievementManager");

}

