#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyAssaultLevelStatistics

#include "Basic.hpp"

#include "PyAssaultLevelStatistics_classes.hpp"
#include "PyAssaultLevelStatistics_parameters.hpp"


namespace SDK
{

// PythonFunction PyAssaultLevelStatistics.PyAssaultLevelStatistics.Initialize
// (Native, Public, BlueprintCallable)

void UPyAssaultLevelStatistics::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAssaultLevelStatistics", "Initialize");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAssaultLevelStatistics.PyAssaultLevelStatistics.Shutdown
// (Native, Public, BlueprintCallable)

void UPyAssaultLevelStatistics::Shutdown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAssaultLevelStatistics", "Shutdown");

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, nullptr);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAssaultLevelStatistics.PyAssaultLevelStatistics.OnObjectiveBegin
// (Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           Obj                                                    (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPyAssaultLevelStatistics::OnObjectiveBegin(class AActor* Obj)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAssaultLevelStatistics", "OnObjectiveBegin");

	Params::PyAssaultLevelStatistics_OnObjectiveBegin Parms{};

	Parms.Obj = Obj;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}


// PythonFunction PyAssaultLevelStatistics.PyAssaultLevelStatistics.OnObjectiveEnd
// (Native, Public, BlueprintCallable)
// Parameters:
// class AActor*                           Obj                                                    (Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UPyAssaultLevelStatistics::OnObjectiveEnd(class AActor* Obj)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PyAssaultLevelStatistics", "OnObjectiveEnd");

	Params::PyAssaultLevelStatistics_OnObjectiveEnd Parms{};

	Parms.Obj = Obj;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;
}

}

