#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyBanPickRuleComponent

#include "Basic.hpp"

#include "MarvelLevel_structs.hpp"
#include "MarvelLevel_classes.hpp"
#include "PyRuleComponent_classes.hpp"
#include "Marvel_structs.hpp"
#include "Python_enums_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// PythonClass PyBanPickRuleComponent.PyBanPickConfig
// 0x0038 (0x0068 - 0x0030)
class UPyBanPickConfig final : public UMarvelRuleConfig
{
public:
	bool                                          EnableBanPick;                                     // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LowestRank;                                        // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LowestRankNum;                                     // 0x0038(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PreSelectHeroTime;                                 // 0x003C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AnnouncementTime;                                  // 0x0040(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickMemberType                            BanPickMemberType;                                 // 0x0044(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickCountingType                          BanPickCountingType;                               // 0x0045(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickModeOrderType                         BanPickModeOrderType;                              // 0x0046(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_47[0x1];                                       // 0x0047(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FBanPickOneSideInfo>            BanPickOneSideList;                                // 0x0048(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	TArray<struct FBanPickBothSideInfo>           BanPickBothSideList;                               // 0x0058(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyBanPickConfig">();
	}
	static class UPyBanPickConfig* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBanPickConfig>();
	}
};
static_assert(alignof(UPyBanPickConfig) == 0x000008, "Wrong alignment on UPyBanPickConfig");
static_assert(sizeof(UPyBanPickConfig) == 0x000068, "Wrong size on UPyBanPickConfig");
static_assert(offsetof(UPyBanPickConfig, EnableBanPick) == 0x000030, "Member 'UPyBanPickConfig::EnableBanPick' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, LowestRank) == 0x000034, "Member 'UPyBanPickConfig::LowestRank' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, LowestRankNum) == 0x000038, "Member 'UPyBanPickConfig::LowestRankNum' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, PreSelectHeroTime) == 0x00003C, "Member 'UPyBanPickConfig::PreSelectHeroTime' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, AnnouncementTime) == 0x000040, "Member 'UPyBanPickConfig::AnnouncementTime' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, BanPickMemberType) == 0x000044, "Member 'UPyBanPickConfig::BanPickMemberType' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, BanPickCountingType) == 0x000045, "Member 'UPyBanPickConfig::BanPickCountingType' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, BanPickModeOrderType) == 0x000046, "Member 'UPyBanPickConfig::BanPickModeOrderType' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, BanPickOneSideList) == 0x000048, "Member 'UPyBanPickConfig::BanPickOneSideList' has a wrong offset!");
static_assert(offsetof(UPyBanPickConfig, BanPickBothSideList) == 0x000058, "Member 'UPyBanPickConfig::BanPickBothSideList' has a wrong offset!");

// PythonClass PyBanPickRuleComponent.PyBanPickRuleComponent
// 0x01F8 (0x02E8 - 0x00F0)
class UPyBanPickRuleComponent final : public UPyRuleComponent
{
public:
	bool                                          EnableBanPick;                                     // 0x00F0(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          ClientEnableBanPick;                               // 0x00F1(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F2[0x2];                                       // 0x00F2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         LowestRank;                                        // 0x00F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LowestRankNum;                                     // 0x00F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         PreSelectHeroTime;                                 // 0x00FC(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         AnnouncementTime;                                  // 0x0100(0x0004)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickMemberType                            BanPickMemberType;                                 // 0x0104(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickOperateType                           BanPickOperateType;                                // 0x0105(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickCountingType                          BanPickCountingType;                               // 0x0106(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickModeOrderType                         BanPickModeOrderType;                              // 0x0107(0x0001)(BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FBanPickOneSideInfo>            BanPickOneSideList;                                // 0x0108(0x0010)(BlueprintVisible, Net, NativeAccessSpecifierPublic)
	TArray<struct FBanPickBothSideInfo>           BanPickBothSideList;                               // 0x0118(0x0010)(BlueprintVisible, Net, NativeAccessSpecifierPublic)
	TArray<struct FBanPickOneSideInfo>            BanPickOneSideInfoList;                            // 0x0128(0x0010)(BlueprintVisible, Net, NativeAccessSpecifierPublic)
	TArray<struct FBanPickResultInfo>             BanPickResultList;                                 // 0x0138(0x0010)(BlueprintVisible, Net, RepNotify, NativeAccessSpecifierPublic)
	struct FBanPickResultInfo                     CurRoundRedBanPickResult;                          // 0x0148(0x0010)(BlueprintVisible, Net, RepNotify, NoDestructor, NativeAccessSpecifierPublic)
	struct FBanPickResultInfo                     CurRoundBlueBanPickResult;                         // 0x0158(0x0010)(BlueprintVisible, Net, RepNotify, NoDestructor, NativeAccessSpecifierPublic)
	EBattleSide                                   CurBanPickSide;                                    // 0x0168(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_169[0x3];                                      // 0x0169(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CurBanPickIndex;                                   // 0x016C(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EBanPickState                                 BanPickState;                                      // 0x0170(0x0001)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_171[0x3];                                      // 0x0171(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RedBanPickLeaderID;                                // 0x0174(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         BlueBanPickLeaderID;                               // 0x0178(0x0004)(BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_17C[0x4];                                      // 0x017C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FReplicateTimer                        PreSelectHeroTimer;                                // 0x0180(0x0078)(BlueprintVisible, Net, NativeAccessSpecifierPublic)
	struct FReplicateTimer                        BanPickHeroTimer;                                  // 0x01F8(0x0078)(BlueprintVisible, Net, NativeAccessSpecifierPublic)
	struct FReplicateTimer                        BanPickAnnouncementTimer;                          // 0x0270(0x0078)(BlueprintVisible, Net, NativeAccessSpecifierPublic)

public:
	void ReceiveEndPlay(EEndPlayReason EndPlayReason);
	void MulticastPreSelectHeroDisplayStageStart();
	void MulticastBanPickDisplayStageStart();
	void S_pre_select_hero_cb();
	void S_ban_pick_hero_time_cb();
	void OnRep_BanPickState();
	void OnRep_BanPickResultList();
	void OnRep_CurRoundRedBanPickResult();
	void OnRep_CurRoundBlueBanPickResult();
	void OnRep_CurBanPickIndex();
	void OnRep_CurBanPickSide();
	void OnRep_RedBanPickLeaderID();
	void OnRep_BlueBanPickLeaderID();
	void OnRep_ClientEnableBanPick();
	void S_end_announcement();
	void Notify_2c_ban_pickstate_time_change(EBanPickState ban_pick_state, float Total_time);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyBanPickRuleComponent">();
	}
	static class UPyBanPickRuleComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyBanPickRuleComponent>();
	}
};
static_assert(alignof(UPyBanPickRuleComponent) == 0x000008, "Wrong alignment on UPyBanPickRuleComponent");
static_assert(sizeof(UPyBanPickRuleComponent) == 0x0002E8, "Wrong size on UPyBanPickRuleComponent");
static_assert(offsetof(UPyBanPickRuleComponent, EnableBanPick) == 0x0000F0, "Member 'UPyBanPickRuleComponent::EnableBanPick' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, ClientEnableBanPick) == 0x0000F1, "Member 'UPyBanPickRuleComponent::ClientEnableBanPick' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, LowestRank) == 0x0000F4, "Member 'UPyBanPickRuleComponent::LowestRank' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, LowestRankNum) == 0x0000F8, "Member 'UPyBanPickRuleComponent::LowestRankNum' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, PreSelectHeroTime) == 0x0000FC, "Member 'UPyBanPickRuleComponent::PreSelectHeroTime' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, AnnouncementTime) == 0x000100, "Member 'UPyBanPickRuleComponent::AnnouncementTime' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickMemberType) == 0x000104, "Member 'UPyBanPickRuleComponent::BanPickMemberType' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickOperateType) == 0x000105, "Member 'UPyBanPickRuleComponent::BanPickOperateType' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickCountingType) == 0x000106, "Member 'UPyBanPickRuleComponent::BanPickCountingType' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickModeOrderType) == 0x000107, "Member 'UPyBanPickRuleComponent::BanPickModeOrderType' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickOneSideList) == 0x000108, "Member 'UPyBanPickRuleComponent::BanPickOneSideList' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickBothSideList) == 0x000118, "Member 'UPyBanPickRuleComponent::BanPickBothSideList' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickOneSideInfoList) == 0x000128, "Member 'UPyBanPickRuleComponent::BanPickOneSideInfoList' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickResultList) == 0x000138, "Member 'UPyBanPickRuleComponent::BanPickResultList' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, CurRoundRedBanPickResult) == 0x000148, "Member 'UPyBanPickRuleComponent::CurRoundRedBanPickResult' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, CurRoundBlueBanPickResult) == 0x000158, "Member 'UPyBanPickRuleComponent::CurRoundBlueBanPickResult' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, CurBanPickSide) == 0x000168, "Member 'UPyBanPickRuleComponent::CurBanPickSide' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, CurBanPickIndex) == 0x00016C, "Member 'UPyBanPickRuleComponent::CurBanPickIndex' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickState) == 0x000170, "Member 'UPyBanPickRuleComponent::BanPickState' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, RedBanPickLeaderID) == 0x000174, "Member 'UPyBanPickRuleComponent::RedBanPickLeaderID' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BlueBanPickLeaderID) == 0x000178, "Member 'UPyBanPickRuleComponent::BlueBanPickLeaderID' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, PreSelectHeroTimer) == 0x000180, "Member 'UPyBanPickRuleComponent::PreSelectHeroTimer' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickHeroTimer) == 0x0001F8, "Member 'UPyBanPickRuleComponent::BanPickHeroTimer' has a wrong offset!");
static_assert(offsetof(UPyBanPickRuleComponent, BanPickAnnouncementTimer) == 0x000270, "Member 'UPyBanPickRuleComponent::BanPickAnnouncementTimer' has a wrong offset!");

}

