#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyRocketRaccoonCharacter

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// DelegateFunction PyRocketRaccoonCharacter.PyRocketRaccoonCharacter.OnCharacterLandedDispatcher__DelegateSignature
// 0x0160 (0x0160 - 0x0000)
struct PyRocketRaccoonCharacter_OnCharacterLandedDispatcher__DelegateSignature final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0160)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PyRocketRaccoonCharacter_OnCharacterLandedDispatcher__DelegateSignature) == 0x000008, "Wrong alignment on PyRocketRaccoonCharacter_OnCharacterLandedDispatcher__DelegateSignature");
static_assert(sizeof(PyRocketRaccoonCharacter_OnCharacterLandedDispatcher__DelegateSignature) == 0x000160, "Wrong size on PyRocketRaccoonCharacter_OnCharacterLandedDispatcher__DelegateSignature");
static_assert(offsetof(PyRocketRaccoonCharacter_OnCharacterLandedDispatcher__DelegateSignature, Hit) == 0x000000, "Member 'PyRocketRaccoonCharacter_OnCharacterLandedDispatcher__DelegateSignature::Hit' has a wrong offset!");

// PythonFunction PyRocketRaccoonCharacter.PyRocketRaccoonCharacter.OnLanded
// 0x0160 (0x0160 - 0x0000)
struct PyRocketRaccoonCharacter_OnLanded final
{
public:
	struct FHitResult                             Hit;                                               // 0x0000(0x0160)(ConstParm, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PyRocketRaccoonCharacter_OnLanded) == 0x000008, "Wrong alignment on PyRocketRaccoonCharacter_OnLanded");
static_assert(sizeof(PyRocketRaccoonCharacter_OnLanded) == 0x000160, "Wrong size on PyRocketRaccoonCharacter_OnLanded");
static_assert(offsetof(PyRocketRaccoonCharacter_OnLanded, Hit) == 0x000000, "Member 'PyRocketRaccoonCharacter_OnLanded::Hit' has a wrong offset!");

}

