#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyTabData_1016

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyTabData_1016.PyTabData_1016.OnActingCharacterKill
// 0x0008 (0x0008 - 0x0000)
struct PyTabData_1016_OnActingCharacterKill final
{
public:
	class AActor*                                 Target;                                            // 0x0000(0x0008)(Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyTabData_1016_OnActingCharacterKill) == 0x000008, "Wrong alignment on PyTabData_1016_OnActingCharacterKill");
static_assert(sizeof(PyTabData_1016_OnActingCharacterKill) == 0x000008, "Wrong size on PyTabData_1016_OnActingCharacterKill");
static_assert(offsetof(PyTabData_1016_OnActingCharacterKill, Target) == 0x000000, "Member 'PyTabData_1016_OnActingCharacterKill::Target' has a wrong offset!");

}

