#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_Ranking_RankRanking

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"
#include "Marvel_structs.hpp"


namespace SDK
{

// PythonClass PyWidget_Ranking_RankRanking.PyWidget_Ranking_BtnMyself
// 0x0000 (0x05E8 - 0x05E8)
class UPyWidget_Ranking_BtnMyself : public UPyMarvelUserWidget
{
public:
	void OnInitialized();
	void Construct();
	void OnHovered();
	void OnUnhovered();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Ranking_BtnMyself">();
	}
	static class UPyWidget_Ranking_BtnMyself* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Ranking_BtnMyself>();
	}
};
static_assert(alignof(UPyWidget_Ranking_BtnMyself) == 0x000008, "Wrong alignment on UPyWidget_Ranking_BtnMyself");
static_assert(sizeof(UPyWidget_Ranking_BtnMyself) == 0x0005E8, "Wrong size on UPyWidget_Ranking_BtnMyself");

// PythonClass PyWidget_Ranking_RankRanking.PyWidget_Ranking_RankRanking
// 0x0010 (0x05F8 - 0x05E8)
class UPyWidget_Ranking_RankRanking : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E1[0x3];                                      // 0x05E1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Intervals;                                         // 0x05E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FGuideTipsStyle>                GuideActions;                                      // 0x05E8(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void PreConstruct(bool IsDesignTime);
	void Construct();
	void Destruct();
	void MarvelSetVisible(bool Visible);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_Ranking_RankRanking">();
	}
	static class UPyWidget_Ranking_RankRanking* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_Ranking_RankRanking>();
	}
};
static_assert(alignof(UPyWidget_Ranking_RankRanking) == 0x000008, "Wrong alignment on UPyWidget_Ranking_RankRanking");
static_assert(sizeof(UPyWidget_Ranking_RankRanking) == 0x0005F8, "Wrong size on UPyWidget_Ranking_RankRanking");
static_assert(offsetof(UPyWidget_Ranking_RankRanking, Intervals) == 0x0005E4, "Member 'UPyWidget_Ranking_RankRanking::Intervals' has a wrong offset!");
static_assert(offsetof(UPyWidget_Ranking_RankRanking, GuideActions) == 0x0005E8, "Member 'UPyWidget_Ranking_RankRanking::GuideActions' has a wrong offset!");

}

