#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_GalleryBook_Card

#include "Basic.hpp"


namespace SDK::Params
{

// DelegateFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.OnGalleryBookClicked__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature final
{
public:
	int32                                         BookIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BookItemID;                                        // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature) == 0x000008, "Wrong alignment on PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature");
static_assert(sizeof(PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature) == 0x000018, "Wrong size on PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature, BookIndex) == 0x000000, "Member 'PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature::BookIndex' has a wrong offset!");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature, BookItemID) == 0x000008, "Member 'PyWidget_GalleryBook_Card_OnGalleryBookClicked__DelegateSignature::BookItemID' has a wrong offset!");

// DelegateFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.OnGalleryBookHovered__DelegateSignature
// 0x0020 (0x0020 - 0x0000)
struct PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature final
{
public:
	int32                                         BookIndex;                                         // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 BookItemID;                                        // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          IsHover_0;                                         // 0x0018(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature) == 0x000008, "Wrong alignment on PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature");
static_assert(sizeof(PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature) == 0x000020, "Wrong size on PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature, BookIndex) == 0x000000, "Member 'PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature::BookIndex' has a wrong offset!");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature, BookItemID) == 0x000008, "Member 'PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature::BookItemID' has a wrong offset!");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature, IsHover_0) == 0x000018, "Member 'PyWidget_GalleryBook_Card_OnGalleryBookHovered__DelegateSignature::IsHover_0' has a wrong offset!");

// DelegateFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.OnGalleryBookPressed__DelegateSignature
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_GalleryBook_Card_OnGalleryBookPressed__DelegateSignature final
{
public:
	bool                                          IsPressed;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_OnGalleryBookPressed__DelegateSignature) == 0x000001, "Wrong alignment on PyWidget_GalleryBook_Card_OnGalleryBookPressed__DelegateSignature");
static_assert(sizeof(PyWidget_GalleryBook_Card_OnGalleryBookPressed__DelegateSignature) == 0x000001, "Wrong size on PyWidget_GalleryBook_Card_OnGalleryBookPressed__DelegateSignature");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnGalleryBookPressed__DelegateSignature, IsPressed) == 0x000000, "Member 'PyWidget_GalleryBook_Card_OnGalleryBookPressed__DelegateSignature::IsPressed' has a wrong offset!");

// PythonFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.MarvelSetVisible
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_GalleryBook_Card_MarvelSetVisible final
{
public:
	bool                                          Visible;                                           // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_MarvelSetVisible) == 0x000001, "Wrong alignment on PyWidget_GalleryBook_Card_MarvelSetVisible");
static_assert(sizeof(PyWidget_GalleryBook_Card_MarvelSetVisible) == 0x000001, "Wrong size on PyWidget_GalleryBook_Card_MarvelSetVisible");
static_assert(offsetof(PyWidget_GalleryBook_Card_MarvelSetVisible, Visible) == 0x000000, "Member 'PyWidget_GalleryBook_Card_MarvelSetVisible::Visible' has a wrong offset!");

// PythonFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.OnAnimationStarted
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_GalleryBook_Card_OnAnimationStarted final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_OnAnimationStarted) == 0x000008, "Wrong alignment on PyWidget_GalleryBook_Card_OnAnimationStarted");
static_assert(sizeof(PyWidget_GalleryBook_Card_OnAnimationStarted) == 0x000008, "Wrong size on PyWidget_GalleryBook_Card_OnAnimationStarted");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnAnimationStarted, Animation) == 0x000000, "Member 'PyWidget_GalleryBook_Card_OnAnimationStarted::Animation' has a wrong offset!");

// PythonFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.OnAnimationFinished
// 0x0008 (0x0008 - 0x0000)
struct PyWidget_GalleryBook_Card_OnAnimationFinished final
{
public:
	const class UWidgetAnimation*                 Animation;                                         // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_OnAnimationFinished) == 0x000008, "Wrong alignment on PyWidget_GalleryBook_Card_OnAnimationFinished");
static_assert(sizeof(PyWidget_GalleryBook_Card_OnAnimationFinished) == 0x000008, "Wrong size on PyWidget_GalleryBook_Card_OnAnimationFinished");
static_assert(offsetof(PyWidget_GalleryBook_Card_OnAnimationFinished, Animation) == 0x000000, "Member 'PyWidget_GalleryBook_Card_OnAnimationFinished::Animation' has a wrong offset!");

// PythonFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.SetIsHover
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_GalleryBook_Card_SetIsHover final
{
public:
	bool                                          IsHover_0;                                         // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_SetIsHover) == 0x000001, "Wrong alignment on PyWidget_GalleryBook_Card_SetIsHover");
static_assert(sizeof(PyWidget_GalleryBook_Card_SetIsHover) == 0x000001, "Wrong size on PyWidget_GalleryBook_Card_SetIsHover");
static_assert(offsetof(PyWidget_GalleryBook_Card_SetIsHover, IsHover_0) == 0x000000, "Member 'PyWidget_GalleryBook_Card_SetIsHover::IsHover_0' has a wrong offset!");

// PythonFunction PyWidget_GalleryBook_Card.PyWidget_GalleryBook_Card.SetBtnIsPressed
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_GalleryBook_Card_SetBtnIsPressed final
{
public:
	bool                                          IsBtnPressed_0;                                    // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_GalleryBook_Card_SetBtnIsPressed) == 0x000001, "Wrong alignment on PyWidget_GalleryBook_Card_SetBtnIsPressed");
static_assert(sizeof(PyWidget_GalleryBook_Card_SetBtnIsPressed) == 0x000001, "Wrong size on PyWidget_GalleryBook_Card_SetBtnIsPressed");
static_assert(offsetof(PyWidget_GalleryBook_Card_SetBtnIsPressed, IsBtnPressed_0) == 0x000000, "Member 'PyWidget_GalleryBook_Card_SetBtnIsPressed::IsBtnPressed_0' has a wrong offset!");

}

