#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_RankRule

#include "Basic.hpp"


namespace SDK::Params
{

// PythonFunction PyWidget_RankRule.PyWidget_RankRule_DisplayRank.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_RankRule_DisplayRank_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_RankRule_DisplayRank_PreConstruct) == 0x000001, "Wrong alignment on PyWidget_RankRule_DisplayRank_PreConstruct");
static_assert(sizeof(PyWidget_RankRule_DisplayRank_PreConstruct) == 0x000001, "Wrong size on PyWidget_RankRule_DisplayRank_PreConstruct");
static_assert(offsetof(PyWidget_RankRule_DisplayRank_PreConstruct, IsDesignTime) == 0x000000, "Member 'PyWidget_RankRule_DisplayRank_PreConstruct::IsDesignTime' has a wrong offset!");

// PythonFunction PyWidget_RankRule.PyWidget_RankRule_RuleInfo.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct PyWidget_RankRule_RuleInfo_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PyWidget_RankRule_RuleInfo_PreConstruct) == 0x000001, "Wrong alignment on PyWidget_RankRule_RuleInfo_PreConstruct");
static_assert(sizeof(PyWidget_RankRule_RuleInfo_PreConstruct) == 0x000001, "Wrong size on PyWidget_RankRule_RuleInfo_PreConstruct");
static_assert(offsetof(PyWidget_RankRule_RuleInfo_PreConstruct, IsDesignTime) == 0x000000, "Member 'PyWidget_RankRule_RuleInfo_PreConstruct::IsDesignTime' has a wrong offset!");

}

