#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PyWidget_PlayerName_WithMarquee

#include "Basic.hpp"

#include "PyMarvelUserWidget_classes.hpp"


namespace SDK
{

// PythonClass PyWidget_PlayerName_WithMarquee.PyWidget_PlayerName_WithMarquee
// 0x0018 (0x0600 - 0x05E8)
class UPyWidget_PlayerName_WithMarquee : public UPyMarvelUserWidget
{
public:
	uint8                                         Pad_5E1[0x7];                                      // 0x05E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UDataTable*                             TextStyleSet;                                      // 0x05E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         TimeInterval_Marquee;                              // 0x05F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Speed_Marquee;                                     // 0x05F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          NeedStartMarqueeDelay;                             // 0x05F8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          NeedJustification_Center;                          // 0x05F9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

public:
	void OnInitialized();
	void Construct();
	void Destruct();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PyWidget_PlayerName_WithMarquee">();
	}
	static class UPyWidget_PlayerName_WithMarquee* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPyWidget_PlayerName_WithMarquee>();
	}
};
static_assert(alignof(UPyWidget_PlayerName_WithMarquee) == 0x000008, "Wrong alignment on UPyWidget_PlayerName_WithMarquee");
static_assert(sizeof(UPyWidget_PlayerName_WithMarquee) == 0x000600, "Wrong size on UPyWidget_PlayerName_WithMarquee");
static_assert(offsetof(UPyWidget_PlayerName_WithMarquee, TextStyleSet) == 0x0005E8, "Member 'UPyWidget_PlayerName_WithMarquee::TextStyleSet' has a wrong offset!");
static_assert(offsetof(UPyWidget_PlayerName_WithMarquee, TimeInterval_Marquee) == 0x0005F0, "Member 'UPyWidget_PlayerName_WithMarquee::TimeInterval_Marquee' has a wrong offset!");
static_assert(offsetof(UPyWidget_PlayerName_WithMarquee, Speed_Marquee) == 0x0005F4, "Member 'UPyWidget_PlayerName_WithMarquee::Speed_Marquee' has a wrong offset!");
static_assert(offsetof(UPyWidget_PlayerName_WithMarquee, NeedStartMarqueeDelay) == 0x0005F8, "Member 'UPyWidget_PlayerName_WithMarquee::NeedStartMarqueeDelay' has a wrong offset!");
static_assert(offsetof(UPyWidget_PlayerName_WithMarquee, NeedJustification_Center) == 0x0005F9, "Member 'UPyWidget_PlayerName_WithMarquee::NeedJustification_Center' has a wrong offset!");

}

