#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HeroSystem_OtherItem

#include "Basic.hpp"

#include "WBP_HeroSystem_OtherItem_classes.hpp"
#include "WBP_HeroSystem_OtherItem_parameters.hpp"


namespace SDK
{

// Function WBP_HeroSystem_OtherItem.WBP_HeroSystem_OtherItem_C.ExecuteUbergraph_WBP_HeroSystem_OtherItem
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HeroSystem_OtherItem_C::ExecuteUbergraph_WBP_HeroSystem_OtherItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeroSystem_OtherItem_C", "ExecuteUbergraph_WBP_HeroSystem_OtherItem");

	Params::WBP_HeroSystem_OtherItem_C_ExecuteUbergraph_WBP_HeroSystem_OtherItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HeroSystem_OtherItem.WBP_HeroSystem_OtherItem_C.RefreshItemEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_HeroSystem_OtherItem_C::RefreshItemEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeroSystem_OtherItem_C", "RefreshItemEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HeroSystem_OtherItem.WBP_HeroSystem_OtherItem_C.SequenceEvent__ENTRYPOINTWBP_HeroSystem_OtherItem
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_HeroSystem_OtherItem_C::SequenceEvent__ENTRYPOINTWBP_HeroSystem_OtherItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeroSystem_OtherItem_C", "SequenceEvent__ENTRYPOINTWBP_HeroSystem_OtherItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HeroSystem_OtherItem.WBP_HeroSystem_OtherItem_C.SequenceEvent__ENTRYPOINTWBP_HeroSystem_OtherItem_0
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_HeroSystem_OtherItem_C::SequenceEvent__ENTRYPOINTWBP_HeroSystem_OtherItem_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HeroSystem_OtherItem_C", "SequenceEvent__ENTRYPOINTWBP_HeroSystem_OtherItem_0");

	UObject::ProcessEvent(Func, nullptr);
}

}

