#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_DropDown_Item_V4

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "PyWidget_DropDownList_ListView_Item_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_DropDown_Item_V4.WBP_DropDown_Item_V4_C
// 0x0078 (0x0800 - 0x0788)
class UWBP_DropDown_Item_V4_C final : public UPyWidget_DropDownList_ListView_Item
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0788(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Anim_Hovered;                                      // 0x0790(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UMarvelHorizontalBox*                   HoriBox_Item;                                      // 0x0798(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Check;                                         // 0x07A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_LeftColor;                                     // 0x07A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Line_C*                            Img_line;                                          // 0x07B0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Mask_Disable;                                  // 0x07B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Privilege_Icon;                                // 0x07C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Tips;                                          // 0x07C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Content;                                   // 0x07D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Main;                                      // 0x07D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_MainBtn;                                   // 0x07E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UScaleBox*                              ScaleBox_Privilege;                                // 0x07E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Main;                                      // 0x07F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_DropDown_Icon_C*                   WBP_DropDown_Icon;                                 // 0x07F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_OnEntryReleased();
	void BP_OnItemExpansionChanged(bool bIsExpanded);
	void BP_OnItemSelectionChanged(bool bIsSelected);
	void ExecuteUbergraph_WBP_DropDown_Item_V4(int32 EntryPoint);
	void OnListItemObjectSet(class UObject* ListItemObject);
	void UnBindAllEvents();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_DropDown_Item_V4_C">();
	}
	static class UWBP_DropDown_Item_V4_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_DropDown_Item_V4_C>();
	}
};
static_assert(alignof(UWBP_DropDown_Item_V4_C) == 0x000008, "Wrong alignment on UWBP_DropDown_Item_V4_C");
static_assert(sizeof(UWBP_DropDown_Item_V4_C) == 0x000800, "Wrong size on UWBP_DropDown_Item_V4_C");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, UberGraphFrame) == 0x000788, "Member 'UWBP_DropDown_Item_V4_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Anim_Hovered) == 0x000790, "Member 'UWBP_DropDown_Item_V4_C::Anim_Hovered' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, HoriBox_Item) == 0x000798, "Member 'UWBP_DropDown_Item_V4_C::HoriBox_Item' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Img_Check) == 0x0007A0, "Member 'UWBP_DropDown_Item_V4_C::Img_Check' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Img_LeftColor) == 0x0007A8, "Member 'UWBP_DropDown_Item_V4_C::Img_LeftColor' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Img_line) == 0x0007B0, "Member 'UWBP_DropDown_Item_V4_C::Img_line' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Img_Mask_Disable) == 0x0007B8, "Member 'UWBP_DropDown_Item_V4_C::Img_Mask_Disable' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Img_Privilege_Icon) == 0x0007C0, "Member 'UWBP_DropDown_Item_V4_C::Img_Privilege_Icon' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Img_Tips) == 0x0007C8, "Member 'UWBP_DropDown_Item_V4_C::Img_Tips' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Overlay_Content) == 0x0007D0, "Member 'UWBP_DropDown_Item_V4_C::Overlay_Content' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Overlay_Main) == 0x0007D8, "Member 'UWBP_DropDown_Item_V4_C::Overlay_Main' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, Overlay_MainBtn) == 0x0007E0, "Member 'UWBP_DropDown_Item_V4_C::Overlay_MainBtn' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, ScaleBox_Privilege) == 0x0007E8, "Member 'UWBP_DropDown_Item_V4_C::ScaleBox_Privilege' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, SizeBox_Main) == 0x0007F0, "Member 'UWBP_DropDown_Item_V4_C::SizeBox_Main' has a wrong offset!");
static_assert(offsetof(UWBP_DropDown_Item_V4_C, WBP_DropDown_Icon) == 0x0007F8, "Member 'UWBP_DropDown_Item_V4_C::WBP_DropDown_Icon' has a wrong offset!");

}

