#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_League_Platform_Group

#include "Basic.hpp"

#include "PyWidget_LeagueMRCObverseCard_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_League_Platform_Group.WBP_League_Platform_Group_C
// 0x0030 (0x0618 - 0x05E8)
class UWBP_League_Platform_Group_C final : public UPyWidget_LeagueMRCObverseCard
{
public:
	class UMarvelImage*                           Img_Done_Icon;                                     // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Done;                                      // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_Goup_Name;                                    // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_Rank_Done;                                    // 0x0600(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_League_Btn_Platform_C*             WBP_League_Btn_Platform_0;                         // 0x0608(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_League_Btn_Platform_C*             WBP_League_Btn_Platform_1;                         // 0x0610(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_League_Platform_Group_C">();
	}
	static class UWBP_League_Platform_Group_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_League_Platform_Group_C>();
	}
};
static_assert(alignof(UWBP_League_Platform_Group_C) == 0x000008, "Wrong alignment on UWBP_League_Platform_Group_C");
static_assert(sizeof(UWBP_League_Platform_Group_C) == 0x000618, "Wrong size on UWBP_League_Platform_Group_C");
static_assert(offsetof(UWBP_League_Platform_Group_C, Img_Done_Icon) == 0x0005E8, "Member 'UWBP_League_Platform_Group_C::Img_Done_Icon' has a wrong offset!");
static_assert(offsetof(UWBP_League_Platform_Group_C, Overlay_Done) == 0x0005F0, "Member 'UWBP_League_Platform_Group_C::Overlay_Done' has a wrong offset!");
static_assert(offsetof(UWBP_League_Platform_Group_C, Text_Goup_Name) == 0x0005F8, "Member 'UWBP_League_Platform_Group_C::Text_Goup_Name' has a wrong offset!");
static_assert(offsetof(UWBP_League_Platform_Group_C, Text_Rank_Done) == 0x000600, "Member 'UWBP_League_Platform_Group_C::Text_Rank_Done' has a wrong offset!");
static_assert(offsetof(UWBP_League_Platform_Group_C, WBP_League_Btn_Platform_0) == 0x000608, "Member 'UWBP_League_Platform_Group_C::WBP_League_Btn_Platform_0' has a wrong offset!");
static_assert(offsetof(UWBP_League_Platform_Group_C, WBP_League_Btn_Platform_1) == 0x000610, "Member 'UWBP_League_Platform_Group_C::WBP_League_Btn_Platform_1' has a wrong offset!");

}

