#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_LeagueSchedule_PageNode

#include "Basic.hpp"

#include "PyWidget_LeagueSchedule_TabBar_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_LeagueSchedule_PageNode.WBP_LeagueSchedule_PageNode_C
// 0x0018 (0x0600 - 0x05E8)
class UWBP_LeagueSchedule_PageNode_C final : public UPyWidget_LeagueSchedule_TabBarPageNode
{
public:
	class UMarvelButton*                          Btn_StagePage;                                     // 0x05E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Page_Hover;                                    // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Page_Selected;                                 // 0x05F8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_LeagueSchedule_PageNode_C">();
	}
	static class UWBP_LeagueSchedule_PageNode_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_LeagueSchedule_PageNode_C>();
	}
};
static_assert(alignof(UWBP_LeagueSchedule_PageNode_C) == 0x000008, "Wrong alignment on UWBP_LeagueSchedule_PageNode_C");
static_assert(sizeof(UWBP_LeagueSchedule_PageNode_C) == 0x000600, "Wrong size on UWBP_LeagueSchedule_PageNode_C");
static_assert(offsetof(UWBP_LeagueSchedule_PageNode_C, Btn_StagePage) == 0x0005E8, "Member 'UWBP_LeagueSchedule_PageNode_C::Btn_StagePage' has a wrong offset!");
static_assert(offsetof(UWBP_LeagueSchedule_PageNode_C, Img_Page_Hover) == 0x0005F0, "Member 'UWBP_LeagueSchedule_PageNode_C::Img_Page_Hover' has a wrong offset!");
static_assert(offsetof(UWBP_LeagueSchedule_PageNode_C, Img_Page_Selected) == 0x0005F8, "Member 'UWBP_LeagueSchedule_PageNode_C::Img_Page_Selected' has a wrong offset!");

}

