#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Setting_WarningColor

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_Setting_WarningColor.WBP_Setting_WarningColor_C
// 0x0040 (0x03F8 - 0x03B8)
class UWBP_Setting_WarningColor_C final : public UUserWidget
{
public:
	class UMarvelImage*                           Img_Chat_Bg;                                       // 0x03B8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelRichTextBlock*                   RichText_Preview_Tips;                             // 0x03C0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelVerticalBox*                     VBox_Chat;                                         // 0x03C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP3D_Dying_C*                         WBP_Dying;                                         // 0x03D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ChatOut_ItemText_Lv2_C*            WBP_ItemText_Warning;                              // 0x03D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Battle_KillReticle_C*              WBP_KillReticle;                                   // 0x03E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Summoned_Dec_V3_C*                 WBP_Summoned;                                      // 0x03E8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_AbilityWarningIndicator_V4_C*      WBP_Warning;                                       // 0x03F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_Setting_WarningColor_C">();
	}
	static class UWBP_Setting_WarningColor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_Setting_WarningColor_C>();
	}
};
static_assert(alignof(UWBP_Setting_WarningColor_C) == 0x000008, "Wrong alignment on UWBP_Setting_WarningColor_C");
static_assert(sizeof(UWBP_Setting_WarningColor_C) == 0x0003F8, "Wrong size on UWBP_Setting_WarningColor_C");
static_assert(offsetof(UWBP_Setting_WarningColor_C, Img_Chat_Bg) == 0x0003B8, "Member 'UWBP_Setting_WarningColor_C::Img_Chat_Bg' has a wrong offset!");
static_assert(offsetof(UWBP_Setting_WarningColor_C, RichText_Preview_Tips) == 0x0003C0, "Member 'UWBP_Setting_WarningColor_C::RichText_Preview_Tips' has a wrong offset!");
static_assert(offsetof(UWBP_Setting_WarningColor_C, VBox_Chat) == 0x0003C8, "Member 'UWBP_Setting_WarningColor_C::VBox_Chat' has a wrong offset!");
static_assert(offsetof(UWBP_Setting_WarningColor_C, WBP_Dying) == 0x0003D0, "Member 'UWBP_Setting_WarningColor_C::WBP_Dying' has a wrong offset!");
static_assert(offsetof(UWBP_Setting_WarningColor_C, WBP_ItemText_Warning) == 0x0003D8, "Member 'UWBP_Setting_WarningColor_C::WBP_ItemText_Warning' has a wrong offset!");
static_assert(offsetof(UWBP_Setting_WarningColor_C, WBP_KillReticle) == 0x0003E0, "Member 'UWBP_Setting_WarningColor_C::WBP_KillReticle' has a wrong offset!");
static_assert(offsetof(UWBP_Setting_WarningColor_C, WBP_Summoned) == 0x0003E8, "Member 'UWBP_Setting_WarningColor_C::WBP_Summoned' has a wrong offset!");
static_assert(offsetof(UWBP_Setting_WarningColor_C, WBP_Warning) == 0x0003F0, "Member 'UWBP_Setting_WarningColor_C::WBP_Warning' has a wrong offset!");

}

