#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BattlePass_Popup

#include "Basic.hpp"


namespace SDK::Params
{

// Function WBP_BattlePass_Popup.WBP_BattlePass_Popup_C.ExecuteUbergraph_WBP_BattlePass_Popup
// 0x0004 (0x0004 - 0x0000)
struct WBP_BattlePass_Popup_C_ExecuteUbergraph_WBP_BattlePass_Popup final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_BattlePass_Popup_C_ExecuteUbergraph_WBP_BattlePass_Popup) == 0x000004, "Wrong alignment on WBP_BattlePass_Popup_C_ExecuteUbergraph_WBP_BattlePass_Popup");
static_assert(sizeof(WBP_BattlePass_Popup_C_ExecuteUbergraph_WBP_BattlePass_Popup) == 0x000004, "Wrong size on WBP_BattlePass_Popup_C_ExecuteUbergraph_WBP_BattlePass_Popup");
static_assert(offsetof(WBP_BattlePass_Popup_C_ExecuteUbergraph_WBP_BattlePass_Popup, EntryPoint) == 0x000000, "Member 'WBP_BattlePass_Popup_C_ExecuteUbergraph_WBP_BattlePass_Popup::EntryPoint' has a wrong offset!");

}

