#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_League_RankingItem

#include "Basic.hpp"

#include "PyWidget_League_Ranking_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_League_RankingItem.WBP_League_RankingItem_C
// 0x01B0 (0x0BE0 - 0x0A30)
class UWBP_League_RankingItem_C final : public UPyWidget_League_RankingItem
{
public:
	class UWidgetAnimation*                       Anim_Flow;                                         // 0x0A30(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UMarvelButton*                          Btn_TeamIcon_Hover_Other;                          // 0x0A38(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelButton*                          Btn_TeamIcon_Hover_Rank1;                          // 0x0A40(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelButton*                          Btn_TeamIcon_Hover_Rank2;                          // 0x0A48(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Common_Ancillary_TeamColor_C*      Btn_Watch;                                         // 0x0A50(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelButton*                          Btn_Watch_Living;                                  // 0x0A58(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_mask;                                          // 0x0A60(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_MySelf_Bg_1;                                   // 0x0A68(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_MySelf_Bg_2;                                   // 0x0A70(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_MySelf_Bg_3;                                   // 0x0A78(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_MySelf_Bg_4;                                   // 0x0A80(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Hover_1;                               // 0x0A88(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Hover_2;                               // 0x0A90(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Hover_3;                               // 0x0A98(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Hover_4;                               // 0x0AA0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_MySelf;                                // 0x0AA8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Normal_1;                              // 0x0AB0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Normal_2;                              // 0x0AB8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Normal_3;                              // 0x0AC0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_Ranking_Normal_4;                              // 0x0AC8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Img_TeamIconBg;                                    // 0x0AD0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage;                                       // 0x0AD8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage_1;                                     // 0x0AE0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage_2;                                     // 0x0AE8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           MarvelImage_204;                                   // 0x0AF0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_BtnWatch;                                  // 0x0AF8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Info_Empty;                                // 0x0B00(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Living;                                    // 0x0B08(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Ranking_Item;                              // 0x0B10(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelOverlay*                         Overlay_Tag_SeedTeam;                              // 0x0B18(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USpacer*                                Spacer_Item;                                       // 0x0B20(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_CompletedSessions;                            // 0x0B28(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_DistanceToPromotion;                          // 0x0B30(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_Integral;                                     // 0x0B38(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelTextBlock*                       Text_Ranking_Number;                               // 0x0B40(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelVerticalBox*                     VBox_ClanInfo;                                     // 0x0B48(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Vx_img_glow;                                       // 0x0B50(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Vx_img_glow01;                                     // 0x0B58(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Vx_Img_Glow02;                                     // 0x0B60(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Vx_Img_Glow03;                                     // 0x0B68(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Vx_Img_Mask;                                       // 0x0B70(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Vx_Img_Mask_1;                                     // 0x0B78(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMarvelImage*                           Vx_Img_Mask_2;                                     // 0x0B80(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Team_ClanIcon_C*                   WBP_ClanIcon;                                      // 0x0B88(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Team_ClanName_Abbreviation_C*      WBP_ClanName_Abbreviation;                         // 0x0B90(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_Team_ClanName_FullName_C*          WBP_ClanName_FullName;                             // 0x0B98(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ComList_Lvx_C*                     WBP_ComList_Ranking_1;                             // 0x0BA0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ComList_Lvx_C*                     WBP_ComList_Ranking_2;                             // 0x0BA8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ComList_Lvx_C*                     WBP_ComList_Ranking_3;                             // 0x0BB0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_ComList_Lvx_C*                     WBP_ComList_Ranking_4;                             // 0x0BB8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_League_Live_News_C*                WBP_League_Live_News_Watch;                        // 0x0BC0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_League_RankingLine_C*              WBP_League_RankingLine;                            // 0x0BC8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_League_TeamIcon_C*                 WBP_League_TeamIcon;                               // 0x0BD0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_Ranking;                            // 0x0BD8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_League_RankingItem_C">();
	}
	static class UWBP_League_RankingItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_League_RankingItem_C>();
	}
};
static_assert(alignof(UWBP_League_RankingItem_C) == 0x000010, "Wrong alignment on UWBP_League_RankingItem_C");
static_assert(sizeof(UWBP_League_RankingItem_C) == 0x000BE0, "Wrong size on UWBP_League_RankingItem_C");
static_assert(offsetof(UWBP_League_RankingItem_C, Anim_Flow) == 0x000A30, "Member 'UWBP_League_RankingItem_C::Anim_Flow' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Btn_TeamIcon_Hover_Other) == 0x000A38, "Member 'UWBP_League_RankingItem_C::Btn_TeamIcon_Hover_Other' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Btn_TeamIcon_Hover_Rank1) == 0x000A40, "Member 'UWBP_League_RankingItem_C::Btn_TeamIcon_Hover_Rank1' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Btn_TeamIcon_Hover_Rank2) == 0x000A48, "Member 'UWBP_League_RankingItem_C::Btn_TeamIcon_Hover_Rank2' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Btn_Watch) == 0x000A50, "Member 'UWBP_League_RankingItem_C::Btn_Watch' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Btn_Watch_Living) == 0x000A58, "Member 'UWBP_League_RankingItem_C::Btn_Watch_Living' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_mask) == 0x000A60, "Member 'UWBP_League_RankingItem_C::Img_mask' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_MySelf_Bg_1) == 0x000A68, "Member 'UWBP_League_RankingItem_C::Img_MySelf_Bg_1' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_MySelf_Bg_2) == 0x000A70, "Member 'UWBP_League_RankingItem_C::Img_MySelf_Bg_2' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_MySelf_Bg_3) == 0x000A78, "Member 'UWBP_League_RankingItem_C::Img_MySelf_Bg_3' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_MySelf_Bg_4) == 0x000A80, "Member 'UWBP_League_RankingItem_C::Img_MySelf_Bg_4' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Hover_1) == 0x000A88, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Hover_1' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Hover_2) == 0x000A90, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Hover_2' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Hover_3) == 0x000A98, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Hover_3' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Hover_4) == 0x000AA0, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Hover_4' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_MySelf) == 0x000AA8, "Member 'UWBP_League_RankingItem_C::Img_Ranking_MySelf' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Normal_1) == 0x000AB0, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Normal_1' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Normal_2) == 0x000AB8, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Normal_2' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Normal_3) == 0x000AC0, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Normal_3' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_Ranking_Normal_4) == 0x000AC8, "Member 'UWBP_League_RankingItem_C::Img_Ranking_Normal_4' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Img_TeamIconBg) == 0x000AD0, "Member 'UWBP_League_RankingItem_C::Img_TeamIconBg' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, MarvelImage) == 0x000AD8, "Member 'UWBP_League_RankingItem_C::MarvelImage' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, MarvelImage_1) == 0x000AE0, "Member 'UWBP_League_RankingItem_C::MarvelImage_1' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, MarvelImage_2) == 0x000AE8, "Member 'UWBP_League_RankingItem_C::MarvelImage_2' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, MarvelImage_204) == 0x000AF0, "Member 'UWBP_League_RankingItem_C::MarvelImage_204' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Overlay_BtnWatch) == 0x000AF8, "Member 'UWBP_League_RankingItem_C::Overlay_BtnWatch' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Overlay_Info_Empty) == 0x000B00, "Member 'UWBP_League_RankingItem_C::Overlay_Info_Empty' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Overlay_Living) == 0x000B08, "Member 'UWBP_League_RankingItem_C::Overlay_Living' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Overlay_Ranking_Item) == 0x000B10, "Member 'UWBP_League_RankingItem_C::Overlay_Ranking_Item' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Overlay_Tag_SeedTeam) == 0x000B18, "Member 'UWBP_League_RankingItem_C::Overlay_Tag_SeedTeam' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Spacer_Item) == 0x000B20, "Member 'UWBP_League_RankingItem_C::Spacer_Item' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Text_CompletedSessions) == 0x000B28, "Member 'UWBP_League_RankingItem_C::Text_CompletedSessions' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Text_DistanceToPromotion) == 0x000B30, "Member 'UWBP_League_RankingItem_C::Text_DistanceToPromotion' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Text_Integral) == 0x000B38, "Member 'UWBP_League_RankingItem_C::Text_Integral' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Text_Ranking_Number) == 0x000B40, "Member 'UWBP_League_RankingItem_C::Text_Ranking_Number' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, VBox_ClanInfo) == 0x000B48, "Member 'UWBP_League_RankingItem_C::VBox_ClanInfo' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Vx_img_glow) == 0x000B50, "Member 'UWBP_League_RankingItem_C::Vx_img_glow' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Vx_img_glow01) == 0x000B58, "Member 'UWBP_League_RankingItem_C::Vx_img_glow01' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Vx_Img_Glow02) == 0x000B60, "Member 'UWBP_League_RankingItem_C::Vx_Img_Glow02' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Vx_Img_Glow03) == 0x000B68, "Member 'UWBP_League_RankingItem_C::Vx_Img_Glow03' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Vx_Img_Mask) == 0x000B70, "Member 'UWBP_League_RankingItem_C::Vx_Img_Mask' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Vx_Img_Mask_1) == 0x000B78, "Member 'UWBP_League_RankingItem_C::Vx_Img_Mask_1' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, Vx_Img_Mask_2) == 0x000B80, "Member 'UWBP_League_RankingItem_C::Vx_Img_Mask_2' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_ClanIcon) == 0x000B88, "Member 'UWBP_League_RankingItem_C::WBP_ClanIcon' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_ClanName_Abbreviation) == 0x000B90, "Member 'UWBP_League_RankingItem_C::WBP_ClanName_Abbreviation' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_ClanName_FullName) == 0x000B98, "Member 'UWBP_League_RankingItem_C::WBP_ClanName_FullName' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_ComList_Ranking_1) == 0x000BA0, "Member 'UWBP_League_RankingItem_C::WBP_ComList_Ranking_1' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_ComList_Ranking_2) == 0x000BA8, "Member 'UWBP_League_RankingItem_C::WBP_ComList_Ranking_2' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_ComList_Ranking_3) == 0x000BB0, "Member 'UWBP_League_RankingItem_C::WBP_ComList_Ranking_3' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_ComList_Ranking_4) == 0x000BB8, "Member 'UWBP_League_RankingItem_C::WBP_ComList_Ranking_4' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_League_Live_News_Watch) == 0x000BC0, "Member 'UWBP_League_RankingItem_C::WBP_League_Live_News_Watch' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_League_RankingLine) == 0x000BC8, "Member 'UWBP_League_RankingItem_C::WBP_League_RankingLine' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WBP_League_TeamIcon) == 0x000BD0, "Member 'UWBP_League_RankingItem_C::WBP_League_TeamIcon' has a wrong offset!");
static_assert(offsetof(UWBP_League_RankingItem_C, WidgetSwitcher_Ranking) == 0x000BD8, "Member 'UWBP_League_RankingItem_C::WidgetSwitcher_Ranking' has a wrong offset!");

}

