#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WP_1033001_ElectricRifle_ShowAnimBP

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "PyShowAnimInstance_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass WP_1033001_ElectricRifle_ShowAnimBP.WP_1033001_ElectricRifle_ShowAnimBP_C
// 0x0460 (0x09B0 - 0x0550)
class UWP_1033001_ElectricRifle_ShowAnimBP_C final : public UPyShowAnimInstance
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0550(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Tag;                        // 0x0558(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0560(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0568(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0570(0x0038)()
	struct FAnimNode_LinkedAnimGraph              AnimGraphNode_LinkedAnimGraph;                     // 0x05A8(0x00D0)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0678(0x0038)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x06B0(0x0038)()
	uint8                                         Pad_6E8[0x8];                                      // 0x06E8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x06F0(0x0260)()
	struct FTransform                             WeaponR;                                           // 0x0950(0x0060)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_WP_1033001_ElectricRifle_ShowAnimBP_AnimGraphNode_ModifyBone_ED25EB0448B932518AB65EBB3E044345();
	void ExecuteUbergraph_WP_1033001_ElectricRifle_ShowAnimBP(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WP_1033001_ElectricRifle_ShowAnimBP_C">();
	}
	static class UWP_1033001_ElectricRifle_ShowAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWP_1033001_ElectricRifle_ShowAnimBP_C>();
	}
};
static_assert(alignof(UWP_1033001_ElectricRifle_ShowAnimBP_C) == 0x000010, "Wrong alignment on UWP_1033001_ElectricRifle_ShowAnimBP_C");
static_assert(sizeof(UWP_1033001_ElectricRifle_ShowAnimBP_C) == 0x0009B0, "Wrong size on UWP_1033001_ElectricRifle_ShowAnimBP_C");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, UberGraphFrame) == 0x000550, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimBlueprintExtension_Tag) == 0x000558, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimBlueprintExtension_Tag' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimBlueprintExtension_PropertyAccess) == 0x000560, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimBlueprintExtension_PropertyAccess' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimBlueprintExtension_Base) == 0x000568, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimBlueprintExtension_Base' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimGraphNode_Root) == 0x000570, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimGraphNode_LinkedAnimGraph) == 0x0005A8, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimGraphNode_LinkedAnimGraph' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimGraphNode_LocalToComponentSpace) == 0x000678, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimGraphNode_ComponentToLocalSpace) == 0x0006B0, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, AnimGraphNode_ModifyBone) == 0x0006F0, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::AnimGraphNode_ModifyBone' has a wrong offset!");
static_assert(offsetof(UWP_1033001_ElectricRifle_ShowAnimBP_C, WeaponR) == 0x000950, "Member 'UWP_1033001_ElectricRifle_ShowAnimBP_C::WeaponR' has a wrong offset!");

}

